services:
  traefik:
    image: traefik:latest
    container_name: meshlogiq-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - meshlogiq-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.meshlogiq.local`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
  db:
    image: timescale/timescaledb-ha:pg18
    container_name: meshlogiq-db
    restart: unless-stopped
    env_file:
      - ./env_files/db.env
    volumes:
      - meshlogiq_pg_data:/home/postgres/pgdata/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - meshlogiq-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meshlogiq-pgadmin
    env_file:
      - ./env_files/pgadmin.env
    environment:
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: 'False'
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['local','meshlogiq.local']"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - meshlogiq_pga_data:/var/lib/pgadmin
    networks:
      - meshlogiq-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.meshlogiq.local`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls=true"
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: meshlogiq-keycloak
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./env_files/keycloak.env
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
      - ./keycloak-themes/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/meshlogiq-theme.jar:ro
    command: ["start", "--proxy-headers", "xforwarded", "--import-realm", "--features=scripts"]
    networks:
      - meshlogiq-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=meshlogiq-env_meshlogiq_network" 
      - "traefik.http.routers.keycloak.rule=Host(`sso.meshlogiq.local`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: meshlogiq-minio
    env_file:
      - ./env_files/minio.env
    command: >
      minio server
      --ftp="address=${MINIO_FTP_ADDRESS:-:8021}"
      --ftp="passive-port-range=${MINIO_FTP_PASSIVE_RANGE:-32000-32100}"
      /data
    volumes:
      - ./minio_data:/data
    networks:
      - meshlogiq-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=meshlogiq-env_meshlogiq_network"
      # ----- Console (UI) -> https://minio.meshlogiq.local  => container:9001
      - "traefik.http.routers.minio-console.rule=Host(`minio.meshlogiq.local`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      # ----- S3 API (path/virtual-host agnostic) -> https://s3.meshlogiq.local => container:9000
      - "traefik.http.routers.minio-s3.rule=Host(`s3.meshlogiq.local`)"
      - "traefik.http.routers.minio-s3.entrypoints=websecure"
      - "traefik.http.routers.minio-s3.tls=true"
      - "traefik.http.routers.minio-s3.service=minio-s3"
      - "traefik.http.services.minio-s3.loadbalancer.server.port=9000"
      # ----- S3 API with bucket subdomain -> https://{bucket}.s3.meshlogiq.local => container:9000
      - "traefik.http.routers.minio-s3-buckets.rule=HostRegexp(`{bucket:.+}.s3.meshlogiq.local`)"
      - "traefik.http.routers.minio-s3-buckets.entrypoints=websecure"
      - "traefik.http.routers.minio-s3-buckets.tls=true"
      - "traefik.http.routers.minio-s3-buckets.service=minio-s3"

volumes:
  meshlogiq_pg_data:
  meshlogiq_pga_data:

networks:
  meshlogiq-net:
    driver: bridge

