export const currency = '$';
export const currentYear = new Date().getFullYear();
export const appName = 'UBold';
export const appTitle = 'UBold - Responsive Bootstrap 5 Admin Dashboard';
export const appDescription = 'UBold is a modern, responsive admin dashboard available on ThemeForest. Ideal for building CRM, CMS, project management tools, and custom web applications with a clean UI, flexible layouts, and rich features.';
export const author = 'Coderthemes';
export const authorWebsite = 'https://coderthemes.com/';
export const authorContact = '';
export const basePath = '';