tls:
  certificates:
    - certFile: /certs/wildcard-fullchain.crt
      keyFile: /certs/wildcard.key
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false

http:
  middlewares:
    secure-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: no-referrer
        sslRedirect: true
    gzip:
      compress: {}

